### ISSUE TITLE
Handle process errors

### ISSUE THREAD

**Issue by sandinmyjoints** [flesler/parallel#1]
Thanks for the helpful lib! A few ideas:
- If any process exits non-zero, then it'd be great if parallel would exit non-zero. This would help when using it in pipelines.
- It'd be great to have an option to exit early as soon as any process has a non-zero exit code, vs. default behavior of continuing until all processes are done.

**Comment by flesler** [comment]
Hi @sandinmyjoints, glad you find it helpful and thanks for the suggestions. I'll bookmark this and (asap) check how GNU Parallel works in those cases. While I don't follow it 100%, I'm not trying to reinvent the wheel but rather port the good parts of it

**Comment by flesler** [comment]
Ok, I checked [GNU parallel docs](https://www.gnu.org/software/parallel/man.html).

About your first point, I like [what they do](https://www.gnu.org/software/parallel/man.html#EXIT-STATUS), exiting with the amount of failed jobs as code. That shouldn't be hard to implement.

Your second point would be the `--halt`/`--halt-on-error` option. I think there's no need to support [that many options](https://www.gnu.org/software/parallel/man.html#halt-on-error-val), a basic boolean should do, at least to get started.

**Comment by sandinmyjoints** [comment]
All that sounds good to me! Would solve the use cases I'm thinking of.

**Comment by flesler** [comment]
@sandinmyjoints Implement both points, please install `1.2.0` and let me know how it goes.
Thanks!

**Comment by sandinmyjoints** [comment]
Awesome, thank you!
